<?php
require_once(__DIR__ . '/simple.ajax.endpoint.inc.php');

$Choices = [
	['value' => 'NORTH-01', 'label' => 'NORTH-01 - North Operations', 'search' => 'NORTH-01 North Operations'],
	['value' => 'EAST-02', 'label' => 'EAST-02 - East Distribution', 'search' => 'EAST-02 East Distribution'],
	['value' => 'LAB-03', 'label' => 'LAB-03 - Product Lab', 'search' => 'LAB-03 Product Lab']
];
?>
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Reusable Operations Toolkit</title>
	<link rel="stylesheet" href="simple.styles.css">
	<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
	<script src="simple.callback.modal.js"></script>
	<script src="simple.search.dropdown.js"></script>
	<script src="simple.report.builder.js"></script>
	<script src="simple.tooltip.js"></script>
	<script src="simple.query.option.js"></script>
</head>
<body>
	<header class="app-header">
		<div class="app-mark">UI</div>
		<div>
			<h1>Reusable Operations Toolkit</h1>
			<div class="app-subtitle">Shared controls and report generation</div>
		</div>
		<nav class="app-nav"><a href="../">Suite Home</a></nav>
	</header>
	<main class="page-shell">
		<section class="panel">
			<div class="panel-title">Callback Dialogs</div>
			<div class="panel-content button-row">
				<button type="button" id="ShowAlert" data-tooltip="Display a reusable notice dialog.">Alert</button>
				<button type="button" id="ShowConfirm" data-tooltip="Request a yes or no decision.">Confirm</button>
				<button type="button" id="ShowPrompt" data-tooltip="Capture a text value through a callback.">Prompt</button>
				<button type="button" id="ShowChoice" data-tooltip="Choose from a generated option list.">Choice</button>
				<button type="button" id="DemoView" data-query-option="view" data-query-title="Demo URL Option" data-query-label="View name" data-tooltip="Store a page option in the URL.">Query Option</button>
			</div>
		</section>
		<section class="panel">
			<div class="panel-title">Searchable Control</div>
			<div class="panel-content">
				<div class="field search-control" style="max-width:420px">
					<label for="SiteSearch">Site</label>
					<input type="text" id="SiteSearch" autocomplete="off" placeholder="Search site code or name">
					<div id="SiteDropdown" class="search-dropdown" style="display:none"></div>
				</div>
			</div>
		</section>
		<section class="panel">
			<div class="panel-title">Shared Reporting</div>
			<div class="panel-content button-row">
				<button type="button" id="PrintReport">Print / Save PDF</button>
				<button type="button" id="DownloadCsv">Download CSV</button>
			</div>
		</section>
	</main>
	<script>
		jQuery(function ($) {
			var Choices = <?php echo json_encode($Choices); ?>;
			var Report = {
				title: 'Operations Toolkit Sample',
				subtitle: 'One definition rendered for print and CSV.',
				meta: [{ label: 'Generated By', value: '<?php echo EncodeHtml(GetDemoUserId()); ?>' }],
				columns: [{ key: 'site', label: 'Site' }, { key: 'assets', label: 'Assets' }, { key: 'status', label: 'Status' }],
				rows: [
					{ site: 'NORTH-01', assets: 5, status: 'Current' },
					{ site: 'EAST-02', assets: 5, status: 'Review' },
					{ site: 'LAB-03', assets: 3, status: 'Current' }
				]
			};

			new SimpleSearchDropdown({
				input: '#SiteSearch',
				menu: '#SiteDropdown',
				items: Choices,
				onSelect: function (Item) {
					SimpleCallbackModal.BuildStatusMessage('Selected ' + Item.value + '.', true);
				}
			});

			$('#ShowAlert').on('click', function () {
				SimpleCallbackModal.Alert('The shared alert keeps application feedback consistent.', 'Reusable Alert');
			});
			$('#ShowConfirm').on('click', function () {
				SimpleCallbackModal.Confirm('Continue with this sample action?', 'Reusable Confirmation', function () {
					SimpleCallbackModal.BuildStatusMessage('Action confirmed.', true);
				});
			});
			$('#ShowPrompt').on('click', function () {
				SimpleCallbackModal.Prompt({
					title: 'Reusable Prompt',
					label: 'Completion notes',
					multiline: true,
					onConfirm: function (Value) {
						SimpleCallbackModal.BuildStatusMessage(Value ? 'Notes captured.' : 'No notes entered.', !!Value);
					}
				});
			});
			$('#ShowChoice').on('click', function () {
				SimpleCallbackModal.Choose({
					title: 'Reusable Choice',
					label: 'Asset type',
					options: ['Endpoint', 'Network Appliance', 'Test Device'],
					onConfirm: function (Value) {
						SimpleCallbackModal.BuildStatusMessage('Selected ' + Value + '.', true);
					}
				});
			});
			$('#PrintReport').on('click', function () { SimpleReportBuilder.Print(Report); });
			$('#DownloadCsv').on('click', function () { SimpleReportBuilder.DownloadCsv(Report, 'operations-toolkit-sample.csv'); });
		});
	</script>
</body>
</html>
